apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 4
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongo
        image: mongo:4.1.9
        ports:
        - containerPort: 27017
      nodeSelector:
        storageType: ssd
        