server:
  port: 9999
  
spring:  application:    name: greetings-client  sleuth:    sampler:      probability: 1.0
    
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
        